---
- name: install spring boot application
  hosts: spring

  pre_tasks:
    - name: install java
      apt:
        name: openjdk-21-jdk
        state: present
        update_cache: yes
      become: yes

  tasks:

    - name: "debug appdir"
      ansible.builtin.debug:
        msg: "appdir {{ ansible_user_dir }}" 
        
    - name: clone git repo
      git:
        repo: 'https://github.com/nikos-kaparos/Crowdfunding.git'
        dest: "{{ appdir }}"
        version: "{{ branch }}"
        force: yes  

    - name: "Populate application.properties"
      lineinfile:
        dest: "{{ appdir }}/backend/src/main/resources/application.properties"
        state: present
        regexp: "^{{item.key}}="
        line: "{{item.key}}={{item.value}}"
      with_items:
        - "{{app.env | dict2items}}"

    - name: Ensure Maven is installed
      apt:
        name: maven
        state: present
        update_cache: yes
      become: yes

    - name: "Build spring project"
      block:

        - name: "Build the Spring application"
          command: "mvn package -Dmaven.test.skip=true"
          args:
              chdir: "{{ appdir }}/backend"

      rescue:

        - name: Fetch the SHA-512 checksum for Maven 3.9.9
          get_url:
            url: https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.zip.sha512
            dest: /tmp/maven_sha512.txt
            validate_certs: yes
            force: yes

        - name: Read the SHA-512 checksum from the file
          command: cat /tmp/maven_sha512.txt
          register: sha512_checksum   

        - name: Replace the distributionSha512Sum line in maven-wrapper.properties
          replace:
            path: "{{ appdir }}/.mvn/wrapper/maven-wrapper.properties"
            regexp: '^distributionSha'
            replace: "distributionSha512Sum={{ sha512_checksum.stdout }}"
        
        - name: Clean up the temporary file
          file:
            path: /tmp/maven_sha512.txt
            state: absent
          when: sha512_checksum is defined 

      always:
          - name: "Build the Spring application"
            command: "mvn package -Dmaven.test.skip=true"
            args:
                chdir: "{{ appdir }}/backend" 

    - name: template spring service file
      template:
        src: ../templates/spring.service.j2
        dest: /etc/systemd/system/spring.service
      become: yes
      notify: restart spring

    - name: reload spring service
      service:
        name: spring
        state: restarted
      become: yes   

    - name: ensure spring service started
      service:
        name: spring
        state: started
        enabled: yes
      become: yes

    - name: "APT - install nginx"
      apt:
        name: nginx
        update_cache: yes
      become: yes

    - name: copy nginx conf file
      template:
        src: ../files/nginx.http.j2
        dest: "/etc/nginx/sites-available/spring"
      become: yes                                                

    - name: enable spring site in nginx
      file:
        src: "/etc/nginx/sites-available/spring"
        dest: "/etc/nginx/sites-enabled/spring"
        state: link
      become: yes
      notify: restart nginx

    - name: de-activate default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      become: yes
      notify: restart nginx

  handlers:
  - name: restart spring
    service:
      name: spring
      state: restarted
    become: yes

  - name: restart nginx
    service:
      name: nginx
      state: restarted
    become: yes   